# Generated by Django 4.1.7 on 2023-03-29 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20230326_1831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='decription',
            new_name='description',
        ),
    ]
